### ISSUE TITLE
pip install fails (cannot find README.md)

### ISSUE THREAD

**Issue by stimko68** [luminousmen/django-sql#1]
Stacktrace:

```
$ sudo -H pip install django-sql
Collecting django-sql
  Downloading django-sql-1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-VA7kXf/django-sql/setup.py", line 5, in <module>
        with io.open('README.md', encoding='utf-8') as f:
    IOError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-VA7kXf/django-sql/
```

System:

* Linux Mint 18
* Python 2.7.12

**Comment by un-def** [comment]
@luminousmen I've fixed this issue (yout forgot to add MANIFEST.in), upload new version (1.0.1) to PyPI please.

**Comment by un-def** [comment]
@stimko68 you can install the app from git:

```
pip install git+https://github.com/luminousmen/django-sql.git
```

**Comment by stimko68** [comment]
Thanks for the quick turnaround; that works:

```
$ sudo -H pip install git+https://github.com/luminousmen/django-sql.git
Collecting git+https://github.com/luminousmen/django-sql.git
  Cloning https://github.com/luminousmen/django-sql.git to /tmp/pip-U_nQIf-build
Installing collected packages: django-sql
  Running setup.py install for django-sql ... done
Successfully installed django-sql-1.0.1
```

**Comment by luminousmen** [comment]
sudo -H pip install django-sql should work now

**Comment by stimko68** [comment]
I confirmed this is working. Thanks!
